# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0009_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userImg',
            field=models.ImageField(upload_to=b''),
        ),
    ]
